version: '3.3'

services:
  postgres:
    container_name: database
    build:
      context: .
      dockerfile: Dockerfile-PG
    networks:
      - postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-pass123}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - postgres
    env_file:
      - .env.example

volumes:
  pgdata:

networks:
  postgres:
    driver: bridge
